### PR TITLE
[ exp ] Let us try and scrap some boilerplate

### PR DESCRIPTION
**Pull request by jfdm**
We need to provide instances and see if Velo is unaffected.

### CODE REVIEW

**Comment by gallais** [comment]
`Reduces` suggests we should define [the reflexive-transitive closure of an arbitrary relation](https://github.com/frex-project/idris-frex/blob/main/src/Data/Relation/Closure/ReflexiveTransitive.idr)
first and then have it a simple alias `Reduces = RTList ReductionStep`

Similarly `Finished` doesn't really need to know about types & terms & scopes,
it seems to me that it's a essentially `Maybe (value tm)`.

**Comment by jfdm** [comment]
Good point! `Reduces` & `Finished` have been boiler plate for so long I lost sight of what else they could be. Especially, as I forget about things like `Rel`, and that `RTList` has been burried in Frex.

**Comment by gallais** [comment]
I've pushed another refactoring pass that drops most of the context/type/term concepts
and makes implicit the parameters that can be reconstructed automatically.

We could additionally re-structure `evaluate` as an

```
data Eval value redux x where
  Nil : value x -> Eval value redux x
  (::) : {y : _} -> redux x y -> Inf (Eval value redux y) -> Eval value redux x

unfold : ((x : a) -> Either (value x) (y ** redux x y)) -> (x : a) -> Eval value redux x
```
and then have a separate function `driver : Fuel -> Eval value redux x -> Maybe (Result value redux x)`
itself implemented in terms of a generic:
```
toRTList : Fuel -> Eval {a} value redux x -> (y ** Maybe (value y) ** RTList redux x y)
```

**Comment by jfdm** [comment]
I think we should look at restructuring `Evaluation.idr` for later. But I will merge this now.

**Pull request merged**
